### ISSUE TITLE
Microceph unit fails when rgw / identity svc relation go away

### ISSUE THREAD

**Issue by gboutry** [canonical/charm-microceph#128]
Log:
```
unit-microceph-2: 15:18:46 ERROR unit.microceph/2.juju-log traefik-route-rgw:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-microceph-2/secret-get', 'secret://e9615935-bed6-44f1-8e05-999731f7fa90/ct3hp2m851jd8pnoag20', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microceph-2/charm/./src/charm.py", line 669, in <module>
    main(MicroCephCharm)
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/./src/charm.py", line 70, in __init__
    super().__init__(framework)
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops_sunbeam/charm.py", line 102, in __init__
    self.relation_handlers = self.get_relation_handlers()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/./src/charm.py", line 338, in get_relation_handlers
    self.id_svc = sunbeam_rhandlers.IdentityServiceRequiresHandler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops_sunbeam/relation_handlers.py", line 544, in __init__
    super().__init__(charm, relation_name, callback_f, mandatory)
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops_sunbeam/relation_handlers.py", line 113, in __init__
    self.set_status(self.status)
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops_sunbeam/relation_handlers.py", line 127, in set_status
    elif self.ready:
         ^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops_sunbeam/relation_handlers.py", line 589, in ready
    return bool(self.interface.service_password)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/lib/charms/keystone_k8s/v1/identity_service.py", line 292, in service_password
    credentials = self.charm.model.get_secret(id=credentials_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/model.py", line 291, in get_secret
    content = self._backend.secret_get(id=id, label=label)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/model.py", line 3552, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-2/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied
```

Bundles:
control-plane.yaml
```
bundle: kubernetes

applications:
  traefik:
    charm: ch:traefik-k8s
    channel: latest/candidate
    base: ubuntu@20.04
    scale: 1
    trust: true
    options:
      kubernetes-service-annotations: metallb.universe.tf/address-pool=public
  mysql:
    charm: ch:mysql-k8s
    channel: 8.0/stable
    base: ubuntu@22.04
    scale: 1
    trust: true
    options:
      profile-limit-memory: 2560
      experimental-max-connections: 150
  keystone:
    charm: ch:keystone-k8s
    channel: 2024.1/edge
    base: ubuntu@24.04
    scale: 1
    trust: true
    storage:
      fernet-keys: 5M
      credential-keys: 5M
    resources:
      keystone-image: ghcr.io/canonical/keystone:2024.1

relations:
- - mysql:database
  - keystone:database
- - traefik:ingress
  - keystone:ingress-internal
---
applications:
  traefik:
    offers:
      http-route:
        endpoints:
          - traefik-route
  keystone:
    offers:
      id-svc:
        endpoints:
          - identity-service
```

microceph.yaml:
```
applications:
  microceph:
    charm: ch:microceph
    channel: latest/edge
    base: ubuntu@24.04
    arch: amd64
    constraints: mem=4G cores=2 root-disk=32G virt-type=virtual-machine
    scale: 3
    options:
      snap-channel: squid/stable
    storage:
      osd-standalone: loop,3,2G
saas:
  keystone:
    url: admin/control-plane.id-svc
  traefik:
    url: admin/control-plane.http-route
relations:
- - keystone
  - microceph:identity-service
- - traefik
  - microceph:traefik-route-rgw
```

Commands:
```
juju add-model control-plane ck8s
juju deploy ./control-plane.yaml --trust
juju add-model cephalopod localhost
juju deploy ./microceph.yaml
juju wait-for application microceph --timeout 600s |& awk 'BEGIN { previous=""; while(getline s){ if (s!=previous) print s; previous=s} }'
for i in 0 1 2; do
  juju wait-for unit microceph/$i --query='workload-status=="active" && agent-status=="idle"'
done
juju destroy-model control-plane --destroy-storage --no-prompt
```

**Comment by gboutry** [comment]
Using the reproducing steps, I see the exact same issue on microceph rev92:

```
unit-microceph-0: 11:10:50 ERROR unit.microceph/0.juju-log identity-service:1: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-microceph-0/secret-get', 'secret://167200ab-2435-4144-806a-f48e20b2eeed/cu3oi6ock1ctfnrshqc0', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microceph-0/charm/./src/charm.py", line 677, in <module>
    main(MicroCephCharm)
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-microceph-0/charm/lib/charms/keystone_k8s/v1/identity_service.py", line 179, in _on_identity_service_relation_changed
    self.service_password
  File "/var/lib/juju/agents/unit-microceph-0/charm/lib/charms/keystone_k8s/v1/identity_service.py", line 292, in service_password
    credentials = self.charm.model.get_secret(id=credentials_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/model.py", line 291, in get_secret
    content = self._backend.secret_get(id=id, label=label)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/model.py", line 3552, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-microceph-0/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied
```

I believe this error comes from sunbeam-ops framework, and has been solved in commit `9de7b1209d70f6925aecd34d6044721c316caf2d`

**Comment by lmlg** [comment]
The charm has been updated to use the latest sunbeam libraries. Please let us know if the issue is still there.
